# encoding: utf-8

### map country name to file name
COUNTRIES = {
  'Austria'   => 'at_austria',
  'Belgium'   => 'be_belgium',
  'Bulgaria'  => 'bg_bulgaria',
  'Croatia'   => 'hr_croatia',
  'Cyprus'    => 'cy_cyprus',
  'Czech Republic' => 'cz_czech_republic',
  'Denmark'   => 'dk_denmark',
  'Estonia'   => 'ee_estonia',
  'Finland'   => 'fi_finland',
  'France'    => 'fr_france',
  'Germany'   => 'de_deutschland',
  'Greece'    => 'gr_greece',
  'Hungary'   => 'hu_hungary',
  'Ireland'   => 'ie_ireland',
  'Italy'     => 'it_italy',
  'Latvia'    => 'lv_latvia',
  'Lithuania'  => 'lt_lithuania',
  'Luxembourg' => 'lu_luxembourg',
  'Malta'      => 'mt_malta',
  'Netherlands' => 'nl_netherlands',
  'Norway'     => 'no_norway',
  'Poland'     => 'pl_poland',
  'Portugal'   => 'pt_portugal',
  'Romania'    => 'ro_romania',
  'Slovakia'   => 'sk_slovakia',
  'Slovenia'   => 'si_slovenia',
  'Spain'      => 'es_espana',
  'Sweden'     => 'se_sweden',
  'Switzerland' => 'ch_switzerland',
  'Turkey'  =>  'tr_turkey',
  'United Kingdom' => 'uk_united_kingdom',
}

